### ISSUE TITLE
Support for integer types

### ISSUE THREAD

**Issue by galah92** [thedumbterminal/jsonschema-bigquery#116]
BigQuery support float, numeric and integer types.
This library convert all numbers to numeric.

Is it possible to add support for integer types as well?

**Comment by thedumbterminal** [comment]
Currently integers are already supported.

Please use a type of `integer` in your JSON schema:

```
{
  "type": "object",
  "properties": {
    "modified": {
      "type": "integer"
    }
  }
}
```

**Comment by galah92** [comment]
Wasn't aware, thanks!

**Comment by thedumbterminal** [comment]
Nothing to do here.
