### ISSUE TITLE
 JSON schema '"additionalProperties": false' isn't present by default

### ISSUE THREAD

**Issue by ahsandar** [thedumbterminal/jsonschema-bigquery#23]
I have a JSON schema generated from API blueprint doc that has MSON definition of the object its a `draft4` version but fails to generate BQ schema due to following error 
```throw new Error(`'object' type properties must have an '"additionalProperties": false' property:\n${JSON.stringify(node, null, 2)}`)``` 
https://github.com/thedumbterminal/jsonschema-bigquery/blob/master/src/converter.js#L139

 is there a workaround to this don't think need to enforce `'"additionalProperties": false'` check.

**Comment by hx-markterry** [comment]
Without the `additionalProperties` check how would you stop datapoints that are not in the schema being sent to the table (into non-existant columns). The assumption here is that a schema is used to create a table then data is sent into the table that adheres to the same schema. Is this how you are using this module?

**Comment by ahsandar** [comment]
If the columns don't exist in BQ schema but the data points have those key-value pair in Json data you would be uploading BQ just ignores those on its own. Also if data gets validated via schema it shouldn't be a concern for BQ if data doesn't match for our case

**Comment by thedumbterminal** [comment]
To be compatible with other use cases we could support options when converting and the additional properties check could be enabled by default with the option to disable it.

Thoughts @paparomeo ?

**Comment by paparomeo** [comment]
:+1: It makes sense to make it optional behind a switch.

**Comment by thedumbterminal** [comment]
@ahsandar Could you have a look at the referenced PR above and see if this meets your needs, thanks.

**Comment by thedumbterminal** [comment]
Will wait for the CLI pr from @ahsandar before releasing v3.

**Comment by thedumbterminal** [comment]
Code changes now in master, will be releasing v3 shortly

**Comment by ahsandar** [comment]
thanks , waiting for v3

**Comment by thedumbterminal** [comment]
V3 now released on npm :-)
