### ISSUE TITLE
I coudn't be able to create a build using either webpak 4 or webpack 5:

### ISSUE THREAD

**Issue by joseignaciorm** [thedumbterminal/jsonschema-bigquery#46]
I am very interested in testing this library into [Bigquery UDFs](https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions), but I coudn't be able to generate the right index.js output either in webpack 4 or webpack 5.
The screenshot below the error I got once I uploaded the index.js webpack built:
 ![udfs](https://user-images.githubusercontent.com/47498082/110467859-ce283e80-80d7-11eb-8e3a-60d671b27f99.PNG)
 
I would appreciate if someone can help me with this problem, as I am new to this and don't have a lot of experience.

**Comment by thedumbterminal** [comment]
This is a serverside module primarily. Could you explain a bit more about how you are trying to use it in a browser and maybe there can be some changes to support your use case, thanks.

**Comment by joseignaciorm** [comment]
> 
> 
> This is a serverside module primarily. Could you explain a bit more about how you are trying to use it in a browser and maybe there can be some changes to support your use case, thanks.

Thank you for replying! Well, I want to use the  `jsonSchemaBigquery.run` method like this (`const bigquerySchema = jsonSchemaBigquery.run(jsonSchemaObject, options)`)  into `Bigquery UDFs` so that I can convert JSON schema to Google BigQuery schema. But as  UDFs can't load npm packages using require from JavaScript e.g: `const jsonSchemaBigquery = require('jsonschema-bigquery')`. I can, however, load external libraries from GCS, packaging `jsonschema-bigquery` library in one output file for example: `index.js` so that I can load it into GCS and could use it with `Bigquery UDFs`. 

In fact, I've loaded others libraries using webpack but this one I coudn't be able because when I try and created, it raises an error like the screenshot above.
If you try package it using webpack you'll see some errors and hints that could help.

This is my webpack.config.js:
```
var path = require("path")

module.exports = {
    entry: [
        "./node_modules/jsonschema-bigquery/src/converter.js"
        ],
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "jsonschema-to-bigquery.js",
        library: "jsonSchemaBigquery",
        libraryTarget: "var",
    },
    stats: {
        errorDetails: false,
    },
    mode: 'production',
}
```

**Comment by thedumbterminal** [comment]
This is how I deploy JS UDFs on BigQuery: https://www.thedumbterminal.co.uk/posts/2021/03/deploying_javascript_functions_on_google_big_query.html

**Comment by thedumbterminal** [comment]
Closing due to no response.
